import Divider from "@mui/material/Divider";
import Head from "next/head";
import { FC, ReactNode } from "react"
import Footer from "./Footer"
import NavBar from "./NavBar"

interface IProps {
    children: ReactNode;
}

const Layout: FC<IProps> = ({children}: IProps) => {
  return (
    <div className="p-4">
        <Head>
        <title>Next.JS Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <NavBar/>
    <Divider sx={{borderBottomWidth: 3}}/>
    <main>{children}</main>
    <Footer/>
    </div>
  )
}

export default Layout